### ISSUE TITLE
Dictionary is very inefficient

### ISSUE THREAD

**Issue by buybackoff** [buybackoff/MMDataStructures#12]
Kernel mutex + 3 writes to different files on add. Could be reduced to one interlocked flag + single file + async writes. For fixed size keys/values it should be possible to boost performance at least 10x fold. And remap for resize could be done similar to lmdb.

**Comment by buybackoff** [comment]
A prototype based on `SCG.Dictionary<K,V>` gives 7Mops writes and 12 Mops reads on MacBook Air (without locks). Lock-free read-write synchronization similar to Spreads.SortedMap will marginally reduce that number. The final implementation will be in the Spreads project.

**Comment by wobba** [comment]
Cool that you're still working on this, and hope you can improve on it :)

**Comment by buybackoff** [comment]
For fixed size key-values performance is over 6 Mops https://github.com/Spreads/Spreads/commit/f49c5d4e5848e4064136e1889f83fe85c7228754
