### ISSUE TITLE
Some handles are not correctly disposed in file manager

### ISSUE THREAD

**Issue by buybackoff** [buybackoff/MMDataStructures#2]
Cannot delete files on dispose if there was no resize. ThreadLocal contained is being disposed before its element?

**Comment by buybackoff** [comment]
we do not close fileStream explicitly in CreateOrOpenFile, probably this is the reason

**Comment by wobba** [comment]
I would think the MemoryMappedFile class would dispose the file stream assigned internally, but perhaps not.

**Comment by buybackoff** [comment]
That is what I hoped for. But cannot find another explanation. Haven't
tested though.

**Comment by wobba** [comment]
This is the Dispose code from the framework, so seems it should be disposed in the finally part.

```
protected virtual void Dispose(bool disposing)
{
    try
    {
        if ((this._handle != null) && !this._handle.IsClosed)
        {
            this._handle.Dispose();
        }
    }
    finally
    {
        if ((this._fileStream != null) && !this._leaveOpen)
        {
            this._fileStream.Dispose();
        }
    }
}

```

**Comment by buybackoff** [comment]
OK, thanks. Saved me one field in another project :)
